steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/marti-api-citas-core', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/marti-api-citas-core']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv:
      - PROVEEDORES_API_CORE_DB_HOST
      - PROVEEDORES_API_CORE_DB_NAME
      - PROVEEDORES_API_CORE_DB_PASSWORD
      - PROVEEDORES_API_CORE_DB_PORT
      - PROVEEDORES_API_CORE_DB_USER
      - CITAS_API_CORE_JWT_SECRET_KEY
      - CITAS_API_CORE_PNJ_COLA
      - CITAS_API_CORE_LLAVE_CIFRADO
      - CITAS_API_CORE_DATA_PROCESSING_COLA
      - CITAS_API_CORE_DATA_REPORTING_COLA
    args:
      - '-c'
      - |
        gcloud run deploy citas-api-core \
          --image gcr.io/$PROJECT_ID/marti-api-citas-core \
          --platform managed \
          --region us-central1 \
          --no-allow-unauthenticated \
          --set-env-vars PORTAL_CITAS_URL=https://citas-portal-onest-logistica-528869640412.us-central1.run.app \
          --set-secrets "PROVEEDORES_API_CORE_DB_HOST=PROVEEDORES_API_CORE_DB_HOST:latest,PROVEEDORES_API_CORE_DB_NAME=PROVEEDORES_API_CORE_DB_NAME:latest,PROVEEDORES_API_CORE_DB_PASSWORD=PROVEEDORES_API_CORE_DB_PASSWORD:latest,PROVEEDORES_API_CORE_DB_PORT=PROVEEDORES_API_CORE_DB_PORT:latest,PROVEEDORES_API_CORE_DB_USER=PROVEEDORES_API_CORE_DB_USER:latest,CITAS_API_CORE_JWT_SECRET_KEY=CITAS_API_CORE_JWT_SECRET_KEY:latest,CITAS_API_CORE_PNJ_COLA=CITAS_API_CORE_PNJ_COLA:latest,CITAS_API_CORE_LLAVE_CIFRADO=CITAS_API_CORE_LLAVE_CIFRADO:latest,CITAS_API_CORE_DATA_PROCESSING_COLA=CITAS_API_CORE_DATA_PROCESSING_COLA:latest,CITAS_API_CORE_DATA_REPORTING_COLA=CITAS_API_CORE_DATA_REPORTING_COLA:latest"

images:
  - 'gcr.io/$PROJECT_ID/marti-api-citas-core'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/marti-deportes-desarrollo/secrets/PROVEEDORES_API_CORE_DB_HOST/versions/latest
      env: PROVEEDORES_API_CORE_DB_HOST
    - versionName: projects/marti-deportes-desarrollo/secrets/PROVEEDORES_API_CORE_DB_NAME/versions/latest
      env: PROVEEDORES_API_CORE_DB_NAME
    - versionName: projects/marti-deportes-desarrollo/secrets/PROVEEDORES_API_CORE_DB_PASSWORD/versions/latest
      env: PROVEEDORES_API_CORE_DB_PASSWORD
    - versionName: projects/marti-deportes-desarrollo/secrets/PROVEEDORES_API_CORE_DB_PORT/versions/latest
      env: PROVEEDORES_API_CORE_DB_PORT
    - versionName: projects/marti-deportes-desarrollo/secrets/PROVEEDORES_API_CORE_DB_USER/versions/latest
      env: PROVEEDORES_API_CORE_DB_USER
    - versionName: projects/marti-deportes-desarrollo/secrets/CITAS_API_CORE_JWT_SECRET_KEY/versions/latest
      env: CITAS_API_CORE_JWT_SECRET_KEY
    - versionName: projects/marti-deportes-desarrollo/secrets/CITAS_API_CORE_PNJ_COLA/versions/latest
      env: CITAS_API_CORE_PNJ_COLA
    - versionName: projects/marti-deportes-desarrollo/secrets/CITAS_API_CORE_LLAVE_CIFRADO/versions/latest
      env: CITAS_API_CORE_LLAVE_CIFRADO
    - versionName: projects/marti-deportes-desarrollo/secrets/CITAS_API_CORE_DATA_PROCESSING_COLA/versions/latest
      env: CITAS_API_CORE_DATA_PROCESSING_COLA
    - versionName: projects/marti-deportes-desarrollo/secrets/CITAS_API_CORE_DATA_REPORTING_COLA/versions/latest
      env: CITAS_API_CORE_DATA_REPORTING_COLA